### ISSUE TITLE
1.14.3 compatibility?

### ISSUE THREAD

**Issue by Column01** [flinbein/PowerNBT#33]
Appears as though that this wonderful plugin has dropped support recently and I would really like to see it get updated for 1.14. I see someone has a github issue open #28 there for a 1.13.1 update but I figured I'd make a new one since it is a different minecraft version.
Error I get when attempting to launch the server with PowerNBT:
```[21:39:52] [Server thread/INFO]: [PowerNBT] Enabling PowerNBT v0.8.9.2*
[21:39:52] [Server thread/ERROR]: Error occurred while enabling PowerNBT v0.8.9.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at me.dpohvar.powernbt.PowerNBT.initializeUtils(PowerNBT.java:135) ~[?:?]
	at me.dpohvar.powernbt.PowerNBT.onEnable(PowerNBT.java:125) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.3.jar:git-Paper-131]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.3.jar:git-Paper-131]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.3.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.3.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.3.jar:git-Paper-131]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.3.jar:git-Paper-131]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.3.jar:git-Paper-131]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859) ~[patched_1.14.3.jar:git-Paper-131]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: no such method
	at me.dpohvar.powernbt.utils.ReflectionUtils$RefClass.findMethodByReturnType(ReflectionUtils.java:365) ~[?:?]
	at me.dpohvar.powernbt.utils.ReflectionUtils$RefClass.findMethodByReturnType(ReflectionUtils.java:330) ~[?:?]
	at me.dpohvar.powernbt.utils.NBTBlockUtils.<init>(NBTBlockUtils.java:26) ~[?:?]
	at me.dpohvar.powernbt.utils.NBTBlockUtils.<clinit>(NBTBlockUtils.java:20) ~[?:?]
	... 11 more
[21:39:52] [Server thread/INFO]: [PowerNBT] Disabling PowerNBT v0.8.9.2
```

**Comment by jounaidr** [comment]
Issue persists with version 1.15

**Comment by mrcoffee1026** [comment]
This project appears to have changed locations, probably developers:  1.16 compatibility is here:
https://github.com/Focusvity/PowerNBT/releases
