### ISSUE TITLE
java.lang.NullPointerException on Load Plugin

### ISSUE THREAD

**Issue by ThorinRS** [flinbein/PowerNBT#40]
Fails to load Plugin on Server with Purpur 1.18.1
```
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getKey()" is null
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:421) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:318) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.jar:git-Purpur-1433]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getKey()" is null
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:78) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:82) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:82) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:82) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:72) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:217) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:165) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:134) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at me.dpohvar.powernbt.PowerNBT.<init>(PowerNBT.java:42) ~[PowerNBT.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        ... 7 more
```

**Comment by DPOH-VAR** [comment]
PowerNBT is not tested with Purpur.
I will try to fix it

**Comment by DPOH-VAR** [comment]
@ThorinRS what is your version of PowerNBT?

**Comment by ThorinRS** [comment]
> @ThorinRS what is your version of PowerNBT?

The latest version (1.1.4).

**Comment by DPOH-VAR** [comment]
@ThorinRS 
I can not reproduce with `git-Purpur-1564 (MC: 1.18.1)` & `PowerNBT 1.1.4`
- Try this snapshot: https://jitpack.io/com/github/flinbein/PowerNBT/fix_npe_40-0.8.4.1-g9470364-78/PowerNBT-fix_npe_40-0.8.4.1-g9470364-78.jar
- try to backup and remove directory `plugins\PowerNBT`

If it helps I will release a next version with patch.

**Comment by ThorinRS** [comment]
> @ThorinRS I can not reproduce with `git-Purpur-1564 (MC: 1.18.1)` & `PowerNBT 1.1.4`
> 
> * Try this snapshot: https://jitpack.io/com/github/flinbein/PowerNBT/fix_npe_40-0.8.4.1-g9470364-78/PowerNBT-fix_npe_40-0.8.4.1-g9470364-78.jar
> * try to backup and remove directory `plugins\PowerNBT`
> 
> If it helps I will release a next version with patch.

With this snapshot, on boot purpur drop this:

`Error occurred while enabling PowerNBT vix_npe_40-0.8.4.1-g9470364-78-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getKey()" is null
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:78) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:82) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:82) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:82) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:72) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:217) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:165) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:134) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at me.dpohvar.powernbt.PowerNBT.onEnable(PowerNBT.java:141) ~[PowerNBT-fix_npe_40-0.8.4.1-g9470364-78.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[purpur-1.18.jar:git-Purpur-1433]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:730) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:506) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:347) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.jar:git-Purpur-1433]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by DPOH-VAR** [comment]
good news!
Reproduced in git-Paper-112 (MC: 1.18.1)

**Comment by dpohvar** [comment]
fixed
https://github.com/flinbein/PowerNBT/releases/tag/v1.1.4.1

**Comment by ghost** [comment]
I'm sorry to bother you so much, I put it here because I suppose it has to do with my using PURPUR and I see a relationship with the above.

When I try to execute any command the console says:

` [PowerNBT] NoClassDefFoundError: Could not initialize class me.dpohvar.powernbt.api.NBTManager`

**Comment by dpohvar** [comment]
Please enable debug mode in `plugins/PowerNBT/config.yml`
```yaml
debug: true
```
and snow me error again and list of plugins

**Comment by ThorinRS** [comment]
This is the error:
`[16:43:26 INFO]: ThorinES issued server command: /pnbt hand
[16:43:26 WARN]: [PowerNBT] Exception on command: pnbt
java.lang.NoClassDefFoundError: Could not initialize class me.dpohvar.powernbt.api.NBTManager
        at me.dpohvar.powernbt.nbt.NBTContainerEntity.readTag(NBTContainerEntity.java:40) ~[PowerNBT (2).jar:?]
        at me.dpohvar.powernbt.nbt.NBTContainerEntity.readTag(NBTContainerEntity.java:15) ~[PowerNBT (2).jar:?]
        at me.dpohvar.powernbt.nbt.NBTContainer.getCustomTag(NBTContainer.java:124) ~[PowerNBT (2).jar:?]
        at me.dpohvar.powernbt.command.action.Argument.getContainer(Argument.java:377) ~[PowerNBT (2).jar:?]
        at me.dpohvar.powernbt.command.action.Argument.<init>(Argument.java:79) ~[PowerNBT (2).jar:?]
        at me.dpohvar.powernbt.command.action.ActionView.<init>(ActionView.java:15) ~[PowerNBT (2).jar:?]
        at me.dpohvar.powernbt.command.action.ActionView.<init>(ActionView.java:19) ~[PowerNBT (2).jar:?]
        at me.dpohvar.powernbt.command.CommandNBT.command(CommandNBT.java:71) ~[PowerNBT (2).jar:?]
        at me.dpohvar.powernbt.command.Command.onCommand(Command.java:30) ~[PowerNBT (2).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2349) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2160) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2141) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1437) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1415) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1408) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1386) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1292) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.jar:git-Purpur-1433]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

And this is my plugin list:
`AbstractMenus, Admin-GUI, AdvancedPortals, AnimaBossBar*, ArmorEquipEvent, AsyncWorldEdit, AuctionHouse, AuthMe, BetterBackpacks, BlockLocker, BlocksHub, CMILib, CommandTimer, CoreProtect, DecentHolograms, DiscordRoleSync*, dynmap, Dynmap-WorldGuard*, Elevator, EpicPluginLib, Essentials, EssentialsDiscord, EssentialsSpawn, Graves, GriefPrevention, GSit, HeadsPlus, HoloDropsX, Images, InfernalMobs, InventoryRollbackPlus, ItemBridge, ItemEdit, ItemsAdder, JDynmapGriefPrevention*, KauriVPN, LibsDisguises, LightAPI, LoneLibs, LPC, LuckPerms, Multiverse-Core, Multiverse-Inventories, NBTAPI, NoteBlockAPI, PacketListenerApi, PlaceholderAPI, PlayerKits, PlayerParticles, PlayMoreSounds, PowerNBT, ProtocolLib, PvPManager, QualityArmory, RealScoreboard, RPGBank, RPGMoney, ScreenEffects, SimpleClans, SkinsRestorer, sleep-most, StackMob, StaffChatReloaded, SuperVanish, TAB, TimeIsMoney, Vault, ViaBackwards, ViaVersion, VoidGen, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags`

**Comment by noah1234fgfdgdsgsgf** [comment]
:)

**Comment by hkkongou** [comment]
same here
plugin cannot use
